### ISSUE TITLE
Sample with screen rotation

### ISSUE THREAD

**Issue by artem-zinnatullin** [pushtorefresh/redom#48]
Related to #12

**Comment by sboishtyan** [comment]
Use ViewModel or another retain primitives for saving state.

**Comment by sboishtyan** [comment]
What do you think about state restoring after the killing of the process?

**Comment by sboishtyan** [comment]
We think that state management is not part of redom functionality.
For this reason, we think you should handle screen rotation by storing the state yourself and then explicitly render that state.
